### ISSUE TITLE
Name your post

### ISSUE THREAD

**Issue by mnsoltis** [neurologic/Comparative-Animal-Behavior#1]
### Name

Noelle Soltis

### The issue location

The issue is found in the Components: Day 2 section under the HQ5 question.

### The original text that raises the issue

What does breading condition do for action specific potential? 

### Your proposed fix

I would change "breading" to "breeding" (i.e. What does breading condition do for action specific potential?)

**Comment by credwards1** [comment]
Also in that same question it says "How does breeding condition effect the stimulus threshold?" where it should be "affect."

**Comment by neurologic** [comment]
Thanks! Fixed.
