### ISSUE TITLE
HQ5 Errors

### ISSUE THREAD

**Issue by credwards1** [neurologic/Comparative-Animal-Behavior#2]
### Name

Ciaran Edwards

### Discussion

In HQ5 it says,

"What does **breading** condition do for action specific potential? How does breeding condition **effect** the stimulus threshold for eliciting a behavior?"

It should say,

"What does **breeding** condition do for action specific potential? How does breeding condition **affect** the stimulus threshold for eliciting a behavior?"

**Comment by neurologic** [comment]
Thanks! Fixed.

Can't help but be embarrassed sometimes when I mix up *effect* and *affect*. Spelling errors are less embarrassing to me for some reason.
