### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mayalicki** [neurologic/Comparative-Animal-Behavior#4]
### Name

Maya Alicki

### The issue location

Under 2/8 Observation day, there is a typo in Q3. 

### The original text that raises the issue

Q3: Come up with a general equation that you could use to calculate the budget for any type of similar data (occurences of possibilities).

### Your proposed fix

Q3: Come up with a general equation that you could use to calculate the budget for any type of similar data (occurrences of possibilities).

I fixed the spelling error of "occurrences".

**Comment by neurologic** [comment]
Thanks! Fixed.
